//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWS_Virus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PWS_Virus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public static byte[] ExtractResources(String filename)
        ///{
        ///    ResourceManager Manager = new ResourceManager(filename, Assembly.GetExecutingAssembly());
        ///    byte[] bytes = (byte[])Manager.GetObject(&quot;pwsdata&quot;);
        ///    return bytes;
        ///}.
        /// </summary>
        internal static string funcManaged {
            get {
                return ResourceManager.GetString("funcManaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DllImport(&quot;kernel32.dll&quot;)]
        ///static extern IntPtr GetModuleHandle(string module);
        ///[DllImport(&quot;kernel32.dll&quot;, SetLastError = true)]
        ///static extern IntPtr FindResource(IntPtr hModule, string lpName, string lpType);
        ///[DllImport(&quot;kernel32.dll&quot;, SetLastError = true)]
        ///static extern IntPtr LoadResource(IntPtr hModule, IntPtr hResInfo);
        ///[DllImport(&quot;kernel32.dll&quot;, SetLastError = true)]
        ///static extern uint SizeofResource(IntPtr hModule, IntPtr hResInfo);
        ///
        ///public static byte[] ExtractResources(String filename)
        ///{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string funcNative {
            get {
                return ResourceManager.GetString("funcNative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RunpeResource {
            get {
                object obj = ResourceManager.GetObject("RunpeResource", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Diagnostics;
        ///using System.IO;
        ///using System.IO.Compression;
        ///using System.Linq;
        ///using System.Reflection;
        ///using System.Resources;
        ///using System.Runtime.InteropServices;
        ///using System.Security.Cryptography;
        ///using System.Text;
        ///using System.Threading;
        ///using System.Threading.Tasks;
        ///using System.Windows.Forms;
        ///
        ///
        ///[assembly: AssemblyTitle(&quot;[title]&quot;)]
        ///[assembly: AssemblyFileVersion(&quot;[fileversion]&quot;)]
        ///[assembly: AssemblyVersion(&quot;[version]&quot;)]
        ///[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stub {
            get {
                return ResourceManager.GetString("stub", resourceCulture);
            }
        }
    }
}
